### ISSUE TITLE
User agent parsing error - https://github.com/sudosammy/knary/blob/master/libknary/http.go#L162

### ISSUE THREAD

**Issue by lo-sec** [sudosammy/knary#17]
When a user agent contains a request verb such as "W**get**/1.15 (linux-gnu)"

We get an output that duplicates the UA as the query

Query: User-Agent: Wget/1.15 (linux-gnu)
User-Agent: Wget/1.15 (linux-gnu)

https://github.com/sudosammy/knary/blob/master/libknary/http.go#L162

I made a change of all request verbs to be appended with a space as a dirty work around - 

+if stringContains(header, "OPTIONS ") ||
+					stringContains(header, "GET ") ||
+					stringContains(header, "POST ") ||
+					stringContains(header, "PUT ") ||
+					stringContains(header, "PATCH ") ||
+					stringContains(header, "DELETE ") {
+					query = header

Hope this helps , thanks for the tool

**Comment by sudosammy** [comment]
Nice find @lo-sec - I can confirm this behaviour and will work on a fix. The whitespace method is appropriate in this case but I'll have a think whether there's a more robust solution. Cheers.

**Comment by sudosammy** [comment]
I can't think of a more elegant method of fixing this. Obviously the whitespace method is going to fail on User-Agent strings like `something get something` but in line with the spec we can always expect a whitespace after the HTTP request type. I've made this change in `2.2.2` and we'll see if it breaks anything 😉
