### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by niah2209** [sudosammy/knary#20]
Can anyone confirm if the webhook for discord is working? I can get Pushover to work, so I know they whole thing is working, I've even checked with tcpdump that it actually is sending data to discordapp.com. Am I using the webhook right?

DISCORD_WEBHOOK=https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}

Haven't tried slack though since we ran out of app integration with our free slack account, but if pushover works, surely discord should work as well, right?

**Comment by sudosammy** [comment]
Hi, thanks for the message. I know Slack and Teams work as expected too. If tcpdump is showing an outbound connection than I would assume it's either a formatting issue with how knary is sending the payload or (far less likely) an issue on their end.

I'll endeavour to investigate more this coming week.

**Comment by niah2209** [comment]
I can confirm it is the formatting. I'm using requestbin.com and can see It looks like it doesn't like how the message is stitched together.

**Comment by sudosammy** [comment]
Thanks, I will endeavour to get to it this week. :)
